# Generated by Django 2.2.16 on 2022-06-26 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220626_1655'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_constraint',
        ),
    ]
